In [1]:

import pandas as pd

import numpy as np

from ilipy import Session
from ilipy.database import DistanceCorrelation
from ilipy import TrackIndex, OdometerTicks

inspection_id = "0ABP0TFUSH1"
num_tracks = 22
environment = "prod"
model_detection_threshold = 0.99

In [2]:
df_with_final_track = pd.read_parquet(f"./insp_{inspection_id}_final_df_us_with_final_track_id.parquet")
display(df_with_final_track)

,view_distance_group,view_distance_start_count,view_distance_start_min,view_distance_start_max,view_distance_start_mean,track_ids,view_distance_stop_min,view_distance_stop_max,view_distance_stop_mean,avg_confidence_mean,avg_confidence_max,avg_confidence_min,sequence_length_mean,sequence_length_sum,max_confidence_by_track,unique_tracks_count,overlap_percent_with_ae,final_track_id
0,6.9,8,6.861793,7.295383,7.040086,"[16, 18]",7.146289,7.504650,7.355713,0.991347,0.9927,0.9905,53.466667,237.000000,"{'0': None, '1': None, '10': None, '11': None,...",2,0.0,16
1,7.8,3,7.791304,7.860076,7.829494,"[8, 15, 19]",7.855114,8.360874,8.032038,0.993700,0.9951,0.9927,113.333333,340.000000,"{'0': None, '1': None, '10': None, '11': None,...",3,0.0,15
2,8.1,2,8.080930,8.151168,8.116049,"[12, 13]",8.151449,8.181559,8.166504,0.993350,0.9941,0.9926,29.000000,58.000000,"{'0': None, '1': None, '10': None, '11': None,...",2,0.0,12
3,8.4,6,8.499537,8.929400,8.499537,"[1, 2, 15]",8.992399,9.651147,9.481325,0.992650,0.9933,0.9920,111.888889,192.333333,"{'0': None, '1': 0.9935, '10': None, '11': Non...",1,0.0,2
4,9.9,1,10.056602,10.056602,10.056602,[17],10.135714,10.135714,10.135714,0.992300,0.9923,0.9923,45.000000,45.000000,"{'0': None, '1': None, '10': None, '11': None,...",1,0.0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20489,201613.2,4,201613.098983,201613.360497,201613.258646,"[3, 4, 14]",201613.293806,201613.583181,201613.439120,0.992200,0.9932,0.9912,101.250000,405.000000,"{'0': None, '1': None, '10': None, '11': None,...",3,0.0,4
20490,201613.5,1,201613.558576,201613.558576,201613.558576,[14],201613.574779,201613.574779,201613.574779,0.990400,0.9904,0.9904,10.000000,10.000000,"{'0': None, '1': None, '10': None, '11': None,...",1,0.0,14
20491,201613.8,1,201613.620981,201613.620981,201613.620981,[4],201614.078179,201614.078179,201614.078179,0.991800,0.9918,0.9918,255.000000,255.000000,"{'0': None, '1': None, '10': None, '11': None,...",1,0.0,4
20492,201615.0,2,201615.085357,201615.101602,201615.093480,"[13, 18]",201615.110066,201615.126502,201615.118284,0.991100,0.9912,0.9910,15.000000,30.000000,"{'0': None, '1': None, '10': None, '11': None,...",2,0.0,13
20493,201620.7,1,201620.937471,201620.937471,201620.937471,[10],201620.971664,201620.971664,201620.971664,0.990800,0.9908,0.9908,20.000000,20.000000,"{'0': None, '1': None, '10': 0.9913, '11': Non...",1,0.0,10

## Upload anomalies

In [3]:
from ilipy import ClipTypes, Session, TrackIndex, ViewDistance
from ilipy.channeldata import ImageProfile
from ilipy.features import Bookmarks
from ilipyutils.ml_features.base import (get_ml_models_info_list, AnomalyStatus)
from ilipyutils.ml_features.insert import FeatureInsert, GeometryCubeParameters
from ili_custom_data.load_model import ModelDataLoader
from ilipy.database import DistanceCorrelation
from ilipyutils.ml_features.overlap import (
    AnomalyOverlapManager,
    OverlapAction,
    OverlapPolicy,
)


session = Session(environment=environment)
session.set_active_inspection(inspection_id)
dist_corr = DistanceCorrelation(session)
bookmarks_interface = Bookmarks(connector=session.database_connector)
latest_model = ModelDataLoader.get_latest_model()

overlap_policy = OverlapPolicy(
    action=OverlapAction.TAG_DUPLICATE,
    min_overlap_iou=0.1,
)
anomaly_overlap_manager = AnomalyOverlapManager(
    overlap_policy=overlap_policy,
    session=session,
    bookmarks_interface=bookmarks_interface,
)
feature_insert = FeatureInsert(
    session=session,
    bookmarks_interface=bookmarks_interface,
    anomaly_overlap_manager=anomaly_overlap_manager, # Set to None to disable overlap checking
)

PySettings.cpp(46): ilipy: Build 0.18.0.12915 c4cd9c78a4 release-ili-0.18 'Thu Dec 18 15:02:49 2025'
PySettings.cpp(47): Paths modulePath: /home/zmirikha/ilipy/lib/python3.11/site-packages/ilipy, userHomePath: /home/zmirikha, identityPath: /home/zmirikha/.aws/ilipy
Settings.cpp(246): Settings: loading settings from /home/zmirikha/ilipy/lib/python3.11/site-packages/ilipy/Data/Environments/defaults.json
Settings.cpp(246): Settings: loading settings from /home/zmirikha/ilipy/lib/python3.11/site-packages/ilipy/Data/Environments/prod.json
PyAuthenticator.cpp(239): Attempting an IAM role login as no username and password or environment variables were provided.
CognitoAuthenticator.cpp(158): Using Cognito Credentials
CognitoAuthenticator.cpp(842): Login Successful.
CognitoAuthenticator.cpp(842): Login Successful.
CognitoAuthenticator.cpp(883): Logged in as username: zahra.mirikharaji
CognitoAuthenticator.cpp(883): Logged in as username: zahra.mirikharaji
DatabaseWebSocket.cpp(153): WebSocket connection established to https://backend.ili-prod.darkvisiontech.com/dbservice/wsbin
DbHealthCheck.cpp(146): Database service health check complete: Healthy
Versioning.cpp(1238): Database schema version=5.3.EC36650D47A2358F, code-generated schema version=5.3.EC36650D47A2358F
HttpRequestPool.cpp(82): [HttpRequestPool] Host: storage-dvv-01.darkvision.local, Port: 8080, Concurrent Connections: 1
HttpRequestPool.cpp(82): [HttpRequestPool] Host: storage-dvh-01.darkvision.local, Port: 8080, Concurrent Connections: 1
RestApi.cpp(72): ApiService Ping Response (http://storage-dvv-01.darkvision.local:8080) : 200, 22ms
RestApi.cpp(72): ApiService Ping Response (http://storage-dvh-01.darkvision.local:8080) : 200, 148ms
PySession.cpp(84): Initialized with inspection: 0ABP0TFUSH1
HttpRequestPool.cpp(82): [HttpRequestPool] Host: storage-dvv-01.darkvision.local, Port: 8080, Concurrent Connections: 3
BasicThreadPool.cpp(20): Initializing SharedThreadPool with 8 threads
DistanceCorrelationController.cpp(247): Loading LegacyDistanceMappings asynchronously for inspection = 0ABP0TFUSH1

In [4]:
cube_params = GeometryCubeParameters(
tlbr_cube_angle_rad=(np.deg2rad(-15), np.deg2rad(15)),
tlbr_probe_scan_angle_rad=(np.deg2rad(-15), np.deg2rad(15)),
tlbr_radial_position_mm=(200-(1.9/2), 200+(1.9/2)),
)
model_info = next(
    model
    for model in get_ml_models_info_list()
    if model.model_name == "Ultrasound-Dent-v1"
)
model_info

MLModelInfo(model_name='Ultrasound-Dent-v1', model_id=14, model_score_bound=[0, 1], anomaly_type_name='DentPlain')

In [5]:

#reset index of final_grouped_bookmarks
final_grouped_bookmarks = df_with_final_track.reset_index(drop=True)
display(final_grouped_bookmarks)

,view_distance_group,view_distance_start_count,view_distance_start_min,view_distance_start_max,view_distance_start_mean,track_ids,view_distance_stop_min,view_distance_stop_max,view_distance_stop_mean,avg_confidence_mean,avg_confidence_max,avg_confidence_min,sequence_length_mean,sequence_length_sum,max_confidence_by_track,unique_tracks_count,overlap_percent_with_ae,final_track_id
0,6.9,8,6.861793,7.295383,7.040086,"[16, 18]",7.146289,7.504650,7.355713,0.991347,0.9927,0.9905,53.466667,237.000000,"{'0': None, '1': None, '10': None, '11': None,...",2,0.0,16
1,7.8,3,7.791304,7.860076,7.829494,"[8, 15, 19]",7.855114,8.360874,8.032038,0.993700,0.9951,0.9927,113.333333,340.000000,"{'0': None, '1': None, '10': None, '11': None,...",3,0.0,15
2,8.1,2,8.080930,8.151168,8.116049,"[12, 13]",8.151449,8.181559,8.166504,0.993350,0.9941,0.9926,29.000000,58.000000,"{'0': None, '1': None, '10': None, '11': None,...",2,0.0,12
3,8.4,6,8.499537,8.929400,8.499537,"[1, 2, 15]",8.992399,9.651147,9.481325,0.992650,0.9933,0.9920,111.888889,192.333333,"{'0': None, '1': 0.9935, '10': None, '11': Non...",1,0.0,2
4,9.9,1,10.056602,10.056602,10.056602,[17],10.135714,10.135714,10.135714,0.992300,0.9923,0.9923,45.000000,45.000000,"{'0': None, '1': None, '10': None, '11': None,...",1,0.0,17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20489,201613.2,4,201613.098983,201613.360497,201613.258646,"[3, 4, 14]",201613.293806,201613.583181,201613.439120,0.992200,0.9932,0.9912,101.250000,405.000000,"{'0': None, '1': None, '10': None, '11': None,...",3,0.0,4
20490,201613.5,1,201613.558576,201613.558576,201613.558576,[14],201613.574779,201613.574779,201613.574779,0.990400,0.9904,0.9904,10.000000,10.000000,"{'0': None, '1': None, '10': None, '11': None,...",1,0.0,14
20491,201613.8,1,201613.620981,201613.620981,201613.620981,[4],201614.078179,201614.078179,201614.078179,0.991800,0.9918,0.9918,255.000000,255.000000,"{'0': None, '1': None, '10': None, '11': None,...",1,0.0,4
20492,201615.0,2,201615.085357,201615.101602,201615.093480,"[13, 18]",201615.110066,201615.126502,201615.118284,0.991100,0.9912,0.9910,15.000000,30.000000,"{'0': None, '1': None, '10': None, '11': None,...",2,0.0,13
20493,201620.7,1,201620.937471,201620.937471,201620.937471,[10],201620.971664,201620.971664,201620.971664,0.990800,0.9908,0.9908,20.000000,20.000000,"{'0': None, '1': None, '10': 0.9913, '11': Non...",1,0.0,10

In [8]:
anomalies = bookmarks_interface.get_anomalies(inspectionId=inspection_id)
dent_anomalies = [a for a in anomalies if "Ultrasound-Dent-v1" in a.tags]
print(f"{len(dent_anomalies)} anomalies with Ultrasound-Dent-v1 tag found in {environment}.")

0 anomalies with Ultrasound-Dent-v1 tag found in prod.

/tmp/ipykernel_1748976/2572833939.py:1: DeprecationWarning: get_anomalies(inspectionId) is deprecated, use get_anomalies with pageOffset and pageSize instead.
  anomalies = bookmarks_interface.get_anomalies(inspectionId=inspection_id)

In [ ]:
#deleted_anomalies = [bookmarks_interface.delete_anomaly(a.feature.anomaly_feature_id) for a in dent_anomalies]

In [9]:

for i, row in final_grouped_bookmarks.iterrows():
        if i<15:
            continue
        profile = ImageProfile.ZeroAngle 
        vd_start, vd_end, track_id = row['view_distance_start_mean'], row['view_distance_stop_mean'], row['final_track_id']

            
        track_nums = (track_id,track_id)
        start_frame_odo_ticks = dist_corr.get_odometer_ticks_from_view_distance(TrackIndex(track_nums[0]), ViewDistance(vd_start)).value
        end_frame_odo_ticks = dist_corr.get_odometer_ticks_from_view_distance(TrackIndex(track_nums[1]), ViewDistance(vd_end)).value
        print(start_frame_odo_ticks)
        print(end_frame_odo_ticks)
        print(f"uploading row {i+1} of {len(final_grouped_bookmarks)}")
        anomaly_info = feature_insert.insert_ml_pred(
        inspection_id=inspection_id,
        tlbr_track_indices=track_nums,
        tlbr_odometer_ticks=(start_frame_odo_ticks, end_frame_odo_ticks),
        cube_params=cube_params,
        model_info=model_info,
        anomaly_status=AnomalyStatus.REVIEW_DETECTION,
        image_profile=profile,
        extra_tags=None,
        # ili_custom_data=model_instance
        )

280021
280903
uploading row 16 of 20494
DbHealthCheck.cpp(146): Database service health check complete: Healthy
283894
298746
uploading row 17 of 20494
302245
309697
uploading row 18 of 20494
319034
319196
uploading row 19 of 20494
322937
327607
uploading row 20 of 20494
327733
328165
uploading row 21 of 20494
336056
336399
uploading row 22 of 20494
339578
339920
uploading row 23 of 20494
342091
342163
uploading row 24 of 20494
354163
354325
uploading row 25 of 20494
372557
375754
uploading row 26 of 20494
371815
372247
uploading row 27 of 20494
389713
390055
uploading row 28 of 20494
399658
405175
uploading row 29 of 20494
418206
418459
uploading row 30 of 20494
418729
418891
uploading row 31 of 20494
424273
435235
uploading row 32 of 20494
447763
448825
uploading row 33 of 20494
476035
480991
uploading row 34 of 20494
530659
535573
uploading row 35 of 20494
543553
547135
uploading row 36 of 20494
592105
596947
uploading row 37 of 20494
647149
648301
uploading row 38 of 20494
659719
660349
uploading row 39 of 20494
684409
684571
uploading row 40 of 20494
693073
693433
uploading row 41 of 20494
697369
697531
uploading row 42 of 20494
714115
719029
uploading row 43 of 20494
727040
732339
uploading row 44 of 20494
746911
747343
uploading row 45 of 20494
789691
792013
uploading row 46 of 20494
793987
794059
uploading row 47 of 20494
816475
817267
uploading row 48 of 20494
816271
817734
uploading row 49 of 20494
821425
822127
uploading row 50 of 20494
862075
864145
uploading row 51 of 20494
957457
957529
uploading row 52 of 20494
1095745
1095817
uploading row 53 of 20494
1192892
1193234
uploading row 54 of 20494
1283522
1283594
uploading row 55 of 20494
1304533
1304785
uploading row 56 of 20494
1372712
1372964
uploading row 57 of 20494
1413752
1414049
uploading row 58 of 20494
1562401
1562671
uploading row 59 of 20494
1892077
1892329
uploading row 60 of 20494
2260125
2260332
uploading row 61 of 20494
2393113
2393365
uploading row 62 of 20494
2426995
2427247
uploading row 63 of 20494
2632288
2632414
uploading row 64 of 20494
2696005
2696347
uploading row 65 of 20494
2782895
2783564
uploading row 66 of 20494
2874223
2874475
uploading row 67 of 20494
2893681
2894023
uploading row 68 of 20494
3048775
3049027
uploading row 69 of 20494
3437521
3437773
uploading row 70 of 20494
3603103
3603535
uploading row 71 of 20494
3760135
3765247
uploading row 72 of 20494
3824113
3824545
uploading row 73 of 20494
3825624
3826447
uploading row 74 of 20494
3969205
3969367
uploading row 75 of 20494
4047527
4052714
uploading row 76 of 20494
4085365
4086067
uploading row 77 of 20494
4107205
4107565
uploading row 78 of 20494
4156288
4161807
uploading row 79 of 20494
4418869
4435394
uploading row 80 of 20494
4446805
4447147
uploading row 81 of 20494
4654237
4657686
uploading row 82 of 20494
4782079
4782331
uploading row 83 of 20494
4953241
4955455
uploading row 84 of 20494
4984543
4990087
uploading row 85 of 20494
5078405
5081260
uploading row 86 of 20494
5166073
5166325
uploading row 87 of 20494
5157430
5159359
uploading row 88 of 20494
5324597
5325753
uploading row 89 of 20494
5325841
5326651
uploading row 90 of 20494
5347897
5347969
uploading row 91 of 20494
5415904
5416255
uploading row 92 of 20494
5464861
5466823
uploading row 93 of 20494
5503021
5507863
uploading row 94 of 20494
5527285
5530417
uploading row 95 of 20494
5551135
5554627
uploading row 96 of 20494
5618665
5625523
uploading row 97 of 20494
5653998
5658875
uploading row 98 of 20494
5688865
5696173
uploading row 99 of 20494
5698999
5699251
uploading row 100 of 20494
5771725
5783677
uploading row 101 of 20494
5836249
5836321
uploading row 102 of 20494
5873242
5881457
uploading row 103 of 20494
5884104
5891110
uploading row 104 of 20494
5896669
5896831
uploading row 105 of 20494
6015673
6017041
uploading row 106 of 20494
6086791
6098743
uploading row 107 of 20494
6202858
6209629
uploading row 108 of 20494
DbHealthCheck.cpp(146): Database service health check complete: Healthy
6215923
6216643
uploading row 109 of 20494
6216887
6217499
uploading row 110 of 20494
6356425
6360547
uploading row 111 of 20494
6424123
6424285
uploading row 112 of 20494
6433274
6439192
uploading row 113 of 20494
6503576
6503918
uploading row 114 of 20494
6512365
6512437
uploading row 115 of 20494
6540229
6540715
uploading row 116 of 20494
6635037
6635739
uploading row 117 of 20494
6681385
6684751
uploading row 118 of 20494
6737893
6739945
uploading row 119 of 20494
6957793
6958135
uploading row 120 of 20494
6959253
6959921
uploading row 121 of 20494
7036291
7040935
uploading row 122 of 20494
7171631
7173413
uploading row 123 of 20494
7428373
7433575
uploading row 124 of 20494
7443313
7448894
uploading row 125 of 20494
7478503
7478845
uploading row 126 of 20494
7485343
7485955
uploading row 127 of 20494
7539607
7541785
uploading row 128 of 20494
7770337
7774729
uploading row 129 of 20494
7819837
7824319
uploading row 130 of 20494
7934383
7942903
uploading row 131 of 20494
8016092
8016704
uploading row 132 of 20494
8121247
8121634
uploading row 133 of 20494
8138377
8138737
uploading row 134 of 20494
8165533
8169835
uploading row 135 of 20494
8259332
8259494
uploading row 136 of 20494
8351066
8353771
uploading row 137 of 20494
8477179
8477251
uploading row 138 of 20494
8535895
8540287
uploading row 139 of 20494
8947364
8947706
uploading row 140 of 20494
9455947
9456379
uploading row 141 of 20494
9523377
9532697
uploading row 142 of 20494
9618163
9619855
uploading row 143 of 20494
9631261
9633709
uploading row 144 of 20494
9634099
9641101
uploading row 145 of 20494
9705955
9706567
uploading row 146 of 20494
9764081
9768593
uploading row 147 of 20494
9763497
9768313
uploading row 148 of 20494
9853237
9858331
uploading row 149 of 20494
9910909
9911431
uploading row 150 of 20494
9993181
9993343
uploading row 151 of 20494
10010863
10016929
uploading row 152 of 20494
10074661
10080577
uploading row 153 of 20494
10131959
10133031
uploading row 154 of 20494
10202965
10203307
uploading row 155 of 20494
10426921
10433023
uploading row 156 of 20494
10493737
10495609
uploading row 157 of 20494
10637917
10638169
uploading row 158 of 20494
10792711
10792873
uploading row 159 of 20494
11024449
11024971
uploading row 160 of 20494
11038129
11052304
uploading row 161 of 20494
11057947
11058379
uploading row 162 of 20494
11079007
11079169
uploading row 163 of 20494
11099258
11099464
uploading row 164 of 20494
11455741
11456876
uploading row 165 of 20494
11457397
11457919
uploading row 166 of 20494
11776201
11776273
uploading row 167 of 20494
12074355
12075481
uploading row 168 of 20494
12088123
12089863
uploading row 169 of 20494
12385243
12385675
uploading row 170 of 20494
12487357
12487708
uploading row 171 of 20494
12509713
12509965
uploading row 172 of 20494
12721669
12722281
uploading row 173 of 20494
12966793
12973525
uploading row 174 of 20494
12973490
12974102
uploading row 175 of 20494
12980401
12980473
uploading row 176 of 20494
12985711
12985783
uploading row 177 of 20494
13010252
13011135
uploading row 178 of 20494
13158005
13166354
uploading row 179 of 20494
13184214
13184392
uploading row 180 of 20494
13222627
13223059
uploading row 181 of 20494
13292701
13292773
uploading row 182 of 20494
13300981
13301233
uploading row 183 of 20494
13313731
13313848
uploading row 184 of 20494
13327111
13327454
uploading row 185 of 20494
13339108
13346202
uploading row 186 of 20494
13383055
13383757
uploading row 187 of 20494
13392021
13392639
uploading row 188 of 20494
13387993
13391035
uploading row 189 of 20494
13424173
13424605
uploading row 190 of 20494
13454287
13454810
uploading row 191 of 20494
13455979
13456843
uploading row 192 of 20494
13458958
13459762
uploading row 193 of 20494
13526989
13527421
uploading row 194 of 20494
13603399
13613244
uploading row 195 of 20494
13821750
13828225
uploading row 196 of 20494
13876729
13876981
uploading row 197 of 20494
13946304
13947603
uploading row 198 of 20494
13990167
13992762
uploading row 199 of 20494
14010001
14010253
uploading row 200 of 20494
14045445
14049467
uploading row 201 of 20494
14094439
14096041
uploading row 202 of 20494
14184262
14185813
uploading row 203 of 20494
14186395
14186647
uploading row 204 of 20494
14266189
14269285
uploading row 205 of 20494
14273217
14273605
uploading row 206 of 20494
DbHealthCheck.cpp(146): Database service health check complete: Healthy
14316355
14318803
uploading row 207 of 20494
14314695
14317648
uploading row 208 of 20494
14321422
14322863
uploading row 209 of 20494
14324059
14325679
uploading row 210 of 20494
14325859
14329855
uploading row 211 of 20494
14404969
14407309
uploading row 212 of 20494
14481349
14481601
uploading row 213 of 20494
14494176
14503785
uploading row 214 of 20494
14498533
14498713
uploading row 215 of 20494
14542469
14551543
uploading row 216 of 20494
14553600
14558358
uploading row 217 of 20494
14630089
14630611
uploading row 218 of 20494
14642734
14648341
uploading row 219 of 20494
14694610
14697249
uploading row 220 of 20494
14701219
14701291
uploading row 221 of 20494
14756047
14756209
uploading row 222 of 20494
14768485
14768737
uploading row 223 of 20494
14786719
14787061
uploading row 224 of 20494
14796659
14797887
uploading row 225 of 20494
14792209
14794429
uploading row 226 of 20494
14847754
14855016
uploading row 227 of 20494
14969107
14969791
uploading row 228 of 20494
14972823
14973457
uploading row 229 of 20494
14972797
14975245
uploading row 230 of 20494
15105571
15106002
uploading row 231 of 20494
15208633
15211990
uploading row 232 of 20494
15243103
15243445
uploading row 233 of 20494
15285312
15288893
uploading row 234 of 20494
15335911
15346945
uploading row 235 of 20494
15363685
15364045
uploading row 236 of 20494
15499897
15500149
uploading row 237 of 20494
15548281
15548713
uploading row 238 of 20494
15556555
15556627
uploading row 239 of 20494
15650695
15650767
uploading row 240 of 20494
15738211
15740101
uploading row 241 of 20494
15733861
15735013
uploading row 242 of 20494
15839266
15840951
uploading row 243 of 20494
15842827
15843637
uploading row 244 of 20494
15903439
15903961
uploading row 245 of 20494
15904196
15904718
uploading row 246 of 20494
15911853
15919722
uploading row 247 of 20494
15921631
15921793
uploading row 248 of 20494
15924048
15925342
uploading row 249 of 20494
15974976
15989617
uploading row 250 of 20494
15986592
15989547
uploading row 251 of 20494
15991009
15993331
uploading row 252 of 20494
16082461
16094233
uploading row 253 of 20494
16096195
16096645
uploading row 254 of 20494
16105789
16107499
uploading row 255 of 20494
16280424
16282488
uploading row 256 of 20494
16274420
16276868
uploading row 257 of 20494
16399291
16399993
uploading row 258 of 20494
16410103
16410355
uploading row 259 of 20494
16401785
16410299
uploading row 260 of 20494
16410787
16412299
uploading row 261 of 20494
16456588
16457804
uploading row 262 of 20494
16502461
16502533
uploading row 263 of 20494
16496821
16499287
uploading row 264 of 20494
16505557
16506830
uploading row 265 of 20494
16513091
16514531
uploading row 266 of 20494
16571978
16574126
uploading row 267 of 20494
16608337
16608589
uploading row 268 of 20494
16653633
16655641
uploading row 269 of 20494
16740379
16746031
uploading row 270 of 20494
16758307
16758379
uploading row 271 of 20494
17240653
17241355
uploading row 272 of 20494
17297515
17298037
uploading row 273 of 20494
17360773
17361835
uploading row 274 of 20494
17373103
17373445
uploading row 275 of 20494
17387719
17388331
uploading row 276 of 20494
17443199
17444189
uploading row 277 of 20494
17443987
17447029
uploading row 278 of 20494
17449440
17450876
uploading row 279 of 20494
17451764
17453492
uploading row 280 of 20494
17455525
17457037
uploading row 281 of 20494
17604001
17607914
uploading row 282 of 20494
17713585
17713747
uploading row 283 of 20494
17938975
17939317
uploading row 284 of 20494
17948755
17955664
uploading row 285 of 20494
17987497
17987749
uploading row 286 of 20494
17993365
17994787
uploading row 287 of 20494
18016186
18023290
uploading row 288 of 20494
18103375
18103447
uploading row 289 of 20494
18147302
18147644
uploading row 290 of 20494
18186109
18186451
uploading row 291 of 20494
18359962
18360354
uploading row 292 of 20494
18415509
18428149
uploading row 293 of 20494
18549673
18552718
uploading row 294 of 20494
18636613
18637045
uploading row 295 of 20494
18639548
18646285
uploading row 296 of 20494
18701314
18701386
uploading row 297 of 20494
18865113
18869112
uploading row 298 of 20494
18935927
18941817
uploading row 299 of 20494
18963191
18963397
uploading row 300 of 20494
19075532
19075604
uploading row 301 of 20494
19168837
19182001
uploading row 302 of 20494
19305957
19309633
uploading row 303 of 20494
19309442
19310504
uploading row 304 of 20494
19317625
19322989
uploading row 305 of 20494
19422085
19422607
uploading row 306 of 20494
19429645
19430077
uploading row 307 of 20494
19450009
19450729
uploading row 308 of 20494
19462846
19469990
uploading row 309 of 20494
19498219
19499101
uploading row 310 of 20494
19497175
19502062
uploading row 311 of 20494
DbHealthCheck.cpp(146): Database service health check complete: Healthy
19505825
19518775
uploading row 312 of 20494
19578415
19585753
uploading row 313 of 20494
19695300
19696003
uploading row 314 of 20494
19701138
19701503
uploading row 315 of 20494
19744237
19744759
uploading row 316 of 20494
19746322
19747609
uploading row 317 of 20494
19773457
19773799
uploading row 318 of 20494
19793784
19795043
uploading row 319 of 20494
19799587
19800019
uploading row 320 of 20494
19848853
19861093
uploading row 321 of 20494
19921831
19928473
uploading row 322 of 20494
19951261
19951693
uploading row 323 of 20494
19952744
19952996
uploading row 324 of 20494
19954321
19955161
uploading row 325 of 20494
19957930
19971356
uploading row 326 of 20494
20103268
20110669
uploading row 327 of 20494
20161423
20161495
uploading row 328 of 20494
20249665
20250187
uploading row 329 of 20494
20312002
20326535
uploading row 330 of 20494
20397535
20397787
uploading row 331 of 20494
20439899
20444857
uploading row 332 of 20494
20449132
20461617
uploading row 333 of 20494
20456771
20464764
uploading row 334 of 20494
20466877
20467129
uploading row 335 of 20494
20474755
20475547
uploading row 336 of 20494
20546035
20548670
uploading row 337 of 20494
20730909
20737512
uploading row 338 of 20494
20774179
20774341
uploading row 339 of 20494
20909671
20912623
uploading row 340 of 20494
20993659
20993731
uploading row 341 of 20494
21001849
21002371
uploading row 342 of 20494
21130434
21147065
uploading row 343 of 20494
21149836
21150696
uploading row 344 of 20494
21161203
21166225
uploading row 345 of 20494
21162271
21162523
uploading row 346 of 20494
21278370
21279673
uploading row 347 of 20494
21281527
21281869
uploading row 348 of 20494
21283356
21285359
uploading row 349 of 20494
21357072
21358055
uploading row 350 of 20494
21357452
21357794
uploading row 351 of 20494
21453379
21455449
uploading row 352 of 20494
21457939
21458821
uploading row 353 of 20494
21458053
21464817
uploading row 354 of 20494
21467527
21471559
uploading row 355 of 20494
21513697
21513769
uploading row 356 of 20494
21571216
21577139
uploading row 357 of 20494
21770605
21770677
uploading row 358 of 20494
21782989
21783511
uploading row 359 of 20494
21784657
21785467
uploading row 360 of 20494
21910215
21911024
uploading row 361 of 20494
21922011
21923623
uploading row 362 of 20494
21989053
21989125
uploading row 363 of 20494
22039042
22052243
uploading row 364 of 20494
22147351
22147693
uploading row 365 of 20494
22214776
22227658
uploading row 366 of 20494
22222717
22223779
uploading row 367 of 20494
22226397
22229057
uploading row 368 of 20494
22233955
22234239
uploading row 369 of 20494
22239744
22247754
uploading row 370 of 20494
22241257
22241509
uploading row 371 of 20494
22256377
22256539
uploading row 372 of 20494
22273747
22274539
uploading row 373 of 20494
22341973
22342315
uploading row 374 of 20494
22406869
22407589
uploading row 375 of 20494
22408998
22415875
uploading row 376 of 20494
22424803
22424875
uploading row 377 of 20494
22446043
22447375
uploading row 378 of 20494
22605631
22606333
uploading row 379 of 20494
22759567
22764158
uploading row 380 of 20494
22764032
22765562
uploading row 381 of 20494
22823759
22825346
uploading row 382 of 20494
22824493
22829695
uploading row 383 of 20494
22829299
22829731
uploading row 384 of 20494
22859413
22859665
uploading row 385 of 20494
22965979
22966231
uploading row 386 of 20494
23025071
23034421
uploading row 387 of 20494
23041062
23047152
uploading row 388 of 20494
23053159
23053699
uploading row 389 of 20494
23059369
23059819
uploading row 390 of 20494
23072371
23074333
uploading row 391 of 20494
23098861
23098933
uploading row 392 of 20494
23105809
23106601
uploading row 393 of 20494
23140883
23148625
uploading row 394 of 20494
23206273
23206435
uploading row 395 of 20494
23283190
23296785
uploading row 396 of 20494
23317118
23317190
uploading row 397 of 20494
23369209
23369371
uploading row 398 of 20494
23436116
23436638
uploading row 399 of 20494
23592144
23596627
uploading row 400 of 20494
23641788
23646503
uploading row 401 of 20494
23670859
23671111
uploading row 402 of 20494
23685681
23688895
uploading row 403 of 20494
23784967
23785327
uploading row 404 of 20494
23833875
23843339
uploading row 405 of 20494
23855109
23870783
uploading row 406 of 20494
23885359
23885611
uploading row 407 of 20494
23931937
23932189
uploading row 408 of 20494
23942768
23957903
uploading row 409 of 20494
23960786
23961398
uploading row 410 of 20494
23966985
23967732
uploading row 411 of 20494
23966996
23967698
uploading row 412 of 20494
23970426
23974544
uploading row 413 of 20494
24080287
24080629
uploading row 414 of 20494
24098389
24098641
uploading row 415 of 20494
24099579
24104297
uploading row 416 of 20494
24098401
24099661
uploading row 417 of 20494
24144830
24144992
uploading row 418 of 20494
24152563
24152725
uploading row 419 of 20494
24199777
24207517
uploading row 420 of 20494
24469375
24470437
uploading row 421 of 20494
24467569
24473855
uploading row 422 of 20494
DbHealthCheck.cpp(146): Database service health check complete: Healthy
24560662
24567291
uploading row 423 of 20494
24701728
24711819
uploading row 424 of 20494
24712736
24712898
uploading row 425 of 20494
24713991
24718924
uploading row 426 of 20494
24739213
24739375
uploading row 427 of 20494
24762163
24762325
uploading row 428 of 20494
24806761
24807013
uploading row 429 of 20494
24845917
24849337
uploading row 430 of 20494
24916822
24924433
uploading row 431 of 20494
24917785
24918397
uploading row 432 of 20494
24981259
24981871
uploading row 433 of 20494
25103167
25106209
uploading row 434 of 20494
25190539
25191871
uploading row 435 of 20494
25239421
25239763
uploading row 436 of 20494
25237981
25238251
uploading row 437 of 20494
25614001
25619185
uploading row 438 of 20494
25624603
25630975
uploading row 439 of 20494
25680349
25680421
uploading row 440 of 20494
25857625
25857697
uploading row 441 of 20494
25880599
25891363
uploading row 442 of 20494
25899697
25905997
uploading row 443 of 20494
25992112
25993021
uploading row 444 of 20494
26057023
26057725
uploading row 445 of 20494
26207167
26208139
uploading row 446 of 20494
26230789
26230951
uploading row 447 of 20494
26305165
26305514
uploading row 448 of 20494
26420053
26420395
uploading row 449 of 20494
26436851
26453667
uploading row 450 of 20494
26453989
26454871
uploading row 451 of 20494
26450586
26451334
uploading row 452 of 20494
26463647
26466229
uploading row 453 of 20494
26737018
26744695
uploading row 454 of 20494
26818627
26819059
uploading row 455 of 20494
26826802
26830332
uploading row 456 of 20494
26874811
26875153
uploading row 457 of 20494
27061469
27063860
uploading row 458 of 20494
27099403
27099925
uploading row 459 of 20494
27187891
27189583
uploading row 460 of 20494
27213397
27213649
uploading row 461 of 20494

In [ ]:
20494-16

20478

DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
CognitoAuthenticator.cpp(842): Login Successful.
CognitoAuthenticator.cpp(883): Logged in as username: zahra.mirikharaji
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy
DbHealthCheck.cpp(146): Database service health check complete: Healthy